# -- Theme Options --
colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["news"]

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "news"
  cardView = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = false
  showZenMode = false

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showCards = false
  groupByYear = true
  orderByWeight = false

[taxonomy]
  showTermCount = true
  cardView = false

[sitemap]
  excludedKinds = []
